apiVersion: v1
kind: Secret
metadata:
  name: finance-secrets
type: Opaque
stringData:
  # Base64 encode in production. Use ExternalSecrets Operator + AWS Secrets Manager for prod.
  db-connection-string: "Host=postgres;Port=5432;Database=financedb;Username=finance;Password=finance"
  aws-access-key: "test"
  aws-secret-key: "test"
